name: "Hyperledger Indy Workflow Setup"
description: "Gets the relevant information for the workflow"

outputs:
  CACHE_KEY_BUILD: 
    description: "A Hash of the Dockerfile for checking if rebuild is needed"
    value: ${{ steps.cache.outputs.CACHE_KEY_BUILD }}
  UBUNTU_VERSION: 
    description: "The ubuntu version for which the packages are built"
    value: ${{ steps.cache.outputs.UBUNTU_VERSION }}
  # Expose the lowercase version of the GitHub repository name
  # to all subsequent jobs that reference image repositories
  # as the push and pull operations require the URL of the repository
  # to be in lowercase.
  GITHUB_REPOSITORY_NAME: 
    description: "lowercase Github Repository name"
    value: ${{ steps.repository-name.outputs.lowercase }}
  distribution:
    description: "The distribution for which the packages are published"
    value: ${{ steps.cache.outputs.distribution }}
  publish:
    description: "A Flag indicating if the packages should be published"
    value: ${{ steps.build-flags.outputs.publish }}

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Convert the GitHub repository name to lowercase
      id: repository-name
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}
    - name: Set outputs
      id: cache
      shell: bash
      run: |
        echo "::set-output name=CACHE_KEY_BUILD::${{ hashFiles('.github/workflows/build/Dockerfile.ubuntu-2004') }}"
        echo "::set-output name=UBUNTU_VERSION::ubuntu-2004"
        echo "::set-output name=distribution::focal"

        # Ensure publishing is only performed when the build is executed from the main (hyperledger/indy-plenum) repository.
        if [[ ${{github.event.repository.full_name}} == 'hyperledger/indy-plenum' && ${{github.event_name}} == 'push'  ]]; then
          echo "::set-output name=publish::true"
        else
          echo "::set-output name=publish::false"
        fi