name: Manual Trigger of Package Build for testing purposes

on:
  push:
    tags:        
      - test**
    
jobs:
  workflow-setup:
    runs-on: ubuntu-latest
    outputs:
      CACHE_KEY_BUILD: ${{ steps.workflow-setup.outputs.CACHE_KEY_BUILD }}
      UBUNTU_VERSION: ${{ steps.workflow-setup.outputs.UBUNTU_VERSION }}
      # Expose the lowercase version of the GitHub repository name
      # to all subsequent jobs that reference image repositories
      # as the push and pull operations require the URL of the repository
      # to be in lowercase.
      GITHUB_REPOSITORY_NAME: ${{ steps.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      distribution: ${{ steps.workflow-setup.outputs.distribution }}    
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: workflow-setup
        id: workflow-setup
        uses: ./.github/actions/workflow-setup

  build_packages:
    name: Build Packages
    uses: ./.github/workflows/reuseable_buildpackages.yaml
    needs: workflow-setup
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
      isDev: 'false'
      isRC: '${{ needs.infos.outputs.isPreRelease }}'
