name: "Publish Artifacts to pypi"

on:
  workflow_call:
    inputs:
      GITHUB_REF:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
      distribution:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN: 
        required: true


jobs:
  publish_artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-20.04
    env:
      GITHUB_REF: ${{ inputs.GITHUB_REF }}
      UBUNTU_VERSION: ${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Download Python Packages from Pipeline Artifacts
        uses: actions/download-artifact@v2
        with:
          name: plenum-python
          path: dist

      - name: Publish Python Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          repository_url: https://test.pypi.org/legacy/

