name: Triggered by Version Bump merged

#disable all tags and enable all brannches and only version file
on:
  push:
    branches-ignore:
      - update-rc-version
      - update-version
    paths:
      - '!**'
      - "plenum/__version__.json"

jobs:
  infos:
    name: infos
    runs-on: ubuntu-latest
    outputs:
      isVersionBump: ${{ steps.get-release-info.outputs.isVersionBump }}
      isPreRelease: ${{ steps.get-release-info.outputs.isRC }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
    steps:
      - name: get-release-info
        id: get-release-info
        uses: ./.github/actions/get-release-info
        with:
          versionString: "${{ github.event.head_commit.message }}"
          
  workflow-setup:
    name: Initialize Workflow
    runs-on: ubuntu-latest
    outputs:
      CACHE_KEY_BUILD: ${{ steps.cache.outputs.CACHE_KEY_BUILD }}
      UBUNTU_VERSION: ${{ steps.cache.outputs.UBUNTU_VERSION }}
      # Expose the lowercase version of the GitHub repository name
      # to all subsequent jobs that reference image repositories
      # as the push and pull operations require the URL of the repository
      # to be in lowercase.
      GITHUB_REPOSITORY_NAME: ${{ steps.repository-name.outputs.lowercase }}
      GITHUB_REF: ${{ steps.cache.outputs.GITHUB_REF }}
      distribution: ${{ steps.cache.outputs.distribution }}
      isDev: ${{ steps.build-flags.outputs.isDev }}
      isRC: ${{ steps.build-flags.outputs.isRC }}
      publish: ${{ steps.build-flags.outputs.publish }}
      version: ${{ steps.cache.outputs.version }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Convert the GitHub repository name to lowercase
        id: repository-name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Set outputs
        id: cache
        run: |
          # Set variables according to version of ubuntu
          if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
            echo "::set-output name=CACHE_KEY_BUILD::${{ hashFiles('.github/workflows/build/Dockerfile.ubuntu-1604') }}"
            echo "::set-output name=UBUNTU_VERSION::ubuntu-1604"
            echo "::set-output name=distribution::xenial"
          fi
          if [[ "${{github.base_ref}}" == "ubuntu-20.04-upgrade" || "${{github.ref}}" == "refs/heads/ubuntu-20.04-upgrade" ]]; then
            echo "::set-output name=CACHE_KEY_BUILD::${{ hashFiles('.github/workflows/build/Dockerfile.ubuntu-2004') }}"
            echo "::set-output name=UBUNTU_VERSION::ubuntu-2004"
            echo "::set-output name=distribution::focal"
          fi

          if [[ "${{github.base_ref}}" == 'master' || "${{github.ref}}" == 'refs/heads/master' || "${{github.base_ref}}" == 'main' || "${{github.ref}}" == 'refs/heads/main' ]]; then
            echo "::set-output name=GITHUB_REF::main"
          elif [[ $(grep -oP "\[\d+.\d+.\d+rc\d+\]" <<< "${{github.event.pull_request.title}}") ]]; then
            echo "::set-output name=GITHUB_REF::rc"
            echo ::set-output\ name=version::$(grep -oP "\d+.\d+.\d+rc\d+" <<< "${{github.event.pull_request.title}}") 
          elif [[ "${{github.base_ref}}" == 'stable' || "${{github.ref}}" == 'refs/heads/stable' ]]; then
            echo "::set-output name=GITHUB_REF::stable"
          else
            echo "::set-output name=GITHUB_REF::dev"
          fi

      - name: Set build flags
        id: build-flags
        run: |

          if [[ "${{steps.cache.outputs.GITHUB_REF}}" == 'dev' || "${{steps.cache.outputs.GITHUB_REF}}" == 'main' ]]; then
            echo "::set-output name=isDev::true"
          else
            echo "::set-output name=isDev::false"
          fi

          if [[ "${{steps.cache.outputs.GITHUB_REF}}" == 'rc' ]]; then
            echo "::set-output name=isRC::true"
          else
            echo "::set-output name=isRC::false"
          fi

          # Ensure publishing is only performed when the build is executed from the main (hyperledger/indy-plenum) repository.
          if [[ ${{github.event.repository.full_name}} == 'hyperledger/indy-plenum' && ${{github.event_name}} == 'push' && ( ${{steps.cache.outputs.GITHUB_REF}} == 'main' || ${{steps.cache.outputs.GITHUB_REF}} == 'rc' || ${{steps.cache.outputs.GITHUB_REF}} == 'stable' || ${{steps.cache.outputs.GITHUB_REF}} == 'dev' ) ]]; then
            echo "::set-output name=publish::true"
          else
            echo "::set-output name=publish::false"
          fi

  lint:
    name: Lint
    needs: [infos]
    if: needs.infos.outputs.isVersionBump == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint
          restore-keys: |
            ${{ runner.os }}-pip-lint
      - name: Install flake8
        run: pip install flake8==3.8.4 pep8==1.7.1 pep8-naming==0.6.1
      - name: Lint with flake8
        run: python3 -m flake8 .


  build-docker-image:
    name: Create Builder Image
    needs: [workflow-setup, lint, infos]
    if: needs.infos.outputs.isVersionBump == 'true'
    uses: ./.github/workflows/buildimage.yaml
    with:
      CACHE_KEY_BUILD: ${{ needs.workflow-setup.outputs.CACHE_KEY_BUILD }}
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}

  plenum_tests:
    name: Test Plenum
    needs: [workflow-setup, infos ,lint, build-docker-image]
    if: needs.infos.outputs.isVersionBump == 'true'
    uses: ./.github/workflows/test.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}

  build_packages:
    name: Build Packages
    needs: [workflow-setup, plenum_tests]
    if: needs.infos.outputs.isVersionBump == 'true'
    uses: ./.github/workflows/buildpackages.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
      isDev: 'false'
      isRC: ${{ needs.infos.outputs.isPreRelease }}

  createRelease:
    name: Create Release
    needs: [infos, build_packages]
    if: needs.infos.outputs.isVersionBump == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Plenum Artifacts from Pipeline Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: PreRelease
        uses: softprops/action-gh-release@v1
        if: needs.infos.outputs.isPreRelease == 'true'
        with:
          tag_name: ${{ needs.infos.outputs.VERSIONTAG }}
          prerelease: true
          files: |
            artifacts/**
          generate_release_notes: true
          body: "[${{ needs.infos.outputs.VERSIONTAG }}] "
          target_commitish: ${{github.event.ref}}
          name: "${{ needs.infos.outputs.VERSIONTAG }}"
          token: ${{ secrets.BOT_PR_PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: needs.infos.outputs.isPreRelease == 'false'
        with:
          tag_name: ${{ needs.infos.outputs.VERSIONTAG }}
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/**
          body: "[${{ needs.infos.outputs.VERSIONTAG }}] "
          target_commitish: ${{github.event.ref}}
          name: "${{ needs.infos.outputs.VERSIONTAG }}"
          token: ${{ secrets.BOT_PR_PAT }}

  publish_artifact_preRelease:
    name: Publish Artifacts
    needs: [workflow-setup, infos ,build_packages]
    if: needs.infos.isPreRelease == 'true'
    uses: ./.github/workflows/publish_artifacts.yaml
    with:
      GITHUB_REF: 'rc'
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
      distribution: ${{ needs.workflow-setup.outputs.distribution }}
    secrets:
      INDY_ARTIFACTORY_REPO_CONFIG: ${{ secrets.INDY_ARTIFACTORY_REPO_CONFIG }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  publish_artifact:
    name: Publish Artifacts
    needs: [workflow-setup, infos, build_packages]
    if: needs.infos.isPreRelease == 'false'
    uses: ./.github/workflows/publish_artifacts.yaml
    with:
      GITHUB_REF: 'stable'
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
      distribution: ${{ needs.workflow-setup.outputs.distribution }}
    secrets:
      INDY_ARTIFACTORY_REPO_CONFIG: ${{ secrets.INDY_ARTIFACTORY_REPO_CONFIG }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}