name: Triggered by set Tag

on:
  push:
    tags:        
      - setRelease-v**

jobs:
  taginfos:
    name: get Tag infos
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-release-info.outputs.version }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
      prBranch: ${{ steps.get-release-info.outputs.prBranch }}
      BASE: ${{ steps.branch.outputs.BASE}}
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: extract branch 
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-output\ name=BASE::$branch
          echo "::debug::BASE is being set to $branch"
      - name: get-release-info
        id: get-release-info
        uses: pschlarb/indy-shared-gha/.github/actions/get-release-info@parametrization
        with:
          versionString: "${{ github.ref }}"


  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install deps for version change
        run: pip install base58
      - name: Prepare package and set version
        run: |
          ./bump_version.sh ${{ needs.taginfos.outputs.VERSION }}

      - name: Create Pull Request
        if: contains(needs.taginfos.outputs.VERSION, 'rc')
        uses: peter-evans/create-pull-request@v3
        with:
          author: ${{ github.actor }} <${{ github.event.pusher.email }}>
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          commit-message: Update Version number for Prerelease
          title: Update Version number for RC[v${{ needs.taginfos.outputs.VERSION }}]
          body: Update Version number for RC[v${{ needs.taginfos.outputs.VERSION }}]
          branch: update-rc-version
          signoff: true
          delete-branch: true
          base: ${{ needs.taginfos.outputs.BASE }}
          token: ${{ secrets.BOT_PR_PAT }}
    
      - name: Create Pull Request
        if:  ${{!contains(needs.taginfos.outputs.VERSION, 'rc')}}
        uses: peter-evans/create-pull-request@v3
        with:
          author: ${{ github.actor }} <${{ github.event.pusher.email }}>
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          commit-message: Update Version number for Release
          title: Update Version number for [v${{ needs.taginfos.outputs.VERSION }}]
          body: Update Version number for [v${{ needs.taginfos.outputs.VERSION }}]
          branch: update-version
          signoff: true
          delete-branch: true
          base: ${{ needs.taginfos.outputs.BASE }}
          token: ${{ secrets.BOT_PR_PAT }}
    