name: Test Artifacts Download

on:
  workflow_dispatch:
    
jobs:
  test:
    name: Test download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download Plenum Artifacts from Github Action Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: releasepr.yaml
          workflow_conclusion: success
          name: plenum-deb
          path: artifacts/plenum-deb
      - name: Download Plenum Artifacts from Github Action Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: releasepr.yaml
          workflow_conclusion: success
          name: plenum-python
          path: artifacts/plenum-python
      - name: Download Plenum Artifacts from Github Action Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: releasepr.yaml
          workflow_conclusion: success
          name: third-party-dependencies
          path: artifacts/third-party-dependencies
      - uses: actions/upload-artifact@v2
        with:
          name: third-party-dependencies
          path: artifacts/third-party-dependencies
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: plenum-deb
          path: artifacts/plenum-deb
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: plenum-python
          path: artifacts/plenum-python
          retention-days: 5